services:
  Plugin\CustomerGroupRank\Security\EventListener\LoginListener:
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    arguments:
      - '@Plugin\CustomerGroupRank\Service\Rank\Context'
      - '@doctrine.orm.default_entity_manager'

  Plugin\CustomerGroupRank\Service\Rank\Rank:
    tags:
      - { name: 'plugin.customer.group.rank', priority: 100 }
    arguments:
      - '@doctrine.orm.default_entity_manager'

